// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkDqv25E7QfO5JsfPNvbHQ2gQzBbqueNs',
    appId: '1:13531524139:web:a13dc21a8df5bfd2878e6e',
    messagingSenderId: '13531524139',
    projectId: 'jonas-job-timer-flutter',
    authDomain: 'jonas-job-timer-flutter.firebaseapp.com',
    storageBucket: 'jonas-job-timer-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgw7tkUGRhvAj5IGhuuIrq4GkpJMvXGC0',
    appId: '1:13531524139:android:b6c6ca034aa74d21878e6e',
    messagingSenderId: '13531524139',
    projectId: 'jonas-job-timer-flutter',
    storageBucket: 'jonas-job-timer-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI_LPq9guJQOCgmxrFZ9h2cw0XhFgnpQw',
    appId: '1:13531524139:ios:3f6ef7e341951468878e6e',
    messagingSenderId: '13531524139',
    projectId: 'jonas-job-timer-flutter',
    storageBucket: 'jonas-job-timer-flutter.appspot.com',
    iosClientId: '13531524139-mnon46vr2j2te92khjor8cn2m4l1k9i9.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobTimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI_LPq9guJQOCgmxrFZ9h2cw0XhFgnpQw',
    appId: '1:13531524139:ios:3f6ef7e341951468878e6e',
    messagingSenderId: '13531524139',
    projectId: 'jonas-job-timer-flutter',
    storageBucket: 'jonas-job-timer-flutter.appspot.com',
    iosClientId: '13531524139-mnon46vr2j2te92khjor8cn2m4l1k9i9.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobTimer',
  );
}
